


services:
  codemonk_db:
    image: postgres:14
    container_name: codemonk_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: codemonk
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: codemonk_backend
    restart: always
    depends_on:
      - codemonk_db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@codemonk_db:5432/codemonk
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload

volumes:
  postgres_data:
